---
title: 例外メッセージ 2 を完了 |Microsoft Docs
ms.custom: ''
ms.date: 06/08/2017
ms.prod: biztalk-server
ms.reviewer: ''
ms.suite: ''
ms.tgt_pltfrm: ''
ms.topic: article
helpviewer_keywords:
- exceptions, completing the flow
ms.assetid: 9cae28f7-6eec-42e1-91ae-ce4db582b90d
caps.latest.revision: 7
author: MandiOhlinger
ms.author: mandia
manager: anneta
ms.openlocfilehash: 053c0569843271fb5d514fa7b59d30353a6268f0
ms.sourcegitcommit: 381e83d43796a345488d54b3f7413e11d56ad7be
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 05/07/2019
ms.locfileid: "65356878"
---
# <a name="completing-the-exception-message"></a>例外完了メッセージ
例外のフローを完了するには、作成、**送信**メッセージし、エラー メッセージ _ 3 を監視対象フォルダーにリダイレクトします。  
  
 ![](../core/media/jdeoneworld-02.gif "JdeOneWorld_02")  
  
## <a name="see-also"></a>参照  
 [例外のキャッチ ブロックを追加する方法](../core/how-to-add-a-catch-exception-block4.md)   
 [BizTalk Server 例外処理の使用](../core/using-biztalk-server-exception-handling1.md)